### ISSUE TITLE
add two recent papers to "generative models"

### ISSUE THREAD

**Issue by AlexandraKapp** [scikit-mobility/DeepLearning4HumanMobility#2]
@misc{berke2022generating,
	title = {Generating synthetic mobility data for a realistic population with {RNNs} to improve utility and privacy},
	author = {Berke, Alex and Doorley, Ronan and Larson, Kent and Moro, Esteban},
	year = {2022},
	url = {http://arxiv.org/abs/2201.01139},
	doi = {10.1145/3477314.3507230}
}

 **DL components:** 
RNN, LSTM

**Evaluation metrics:** 
Utility: KL divergence on trip distance / locations per user / aggregate time per location, home / work label error rate
Privacy:  similarity between any synthetic trajectory and any real trajectory 

**Code:** 
https://github.com/aberke/lbs-data/tree/master/trajectory_synthesis

-----

@misc{zhan2022privacyaware,
      title={Privacy-Aware Human Mobility Prediction via Adversarial Networks}, 
      author={Yuting Zhan and Alex Kyllo and Afra Mashhadi and Hamed Haddadi},
      year={2022},
      eprint={2201.07519},
      archivePrefix={arXiv},
      primaryClass={cs.LG}
}

**name of the model:** LSTM-PAE 

 **DL components:**
LSTM, adversarial learning

**Evaluation metrics:** 
prediction accuracy (U), information loss in the reconstruction process (PI), user re-identification inaccuracy (PII)

**Comment by MassimilianoLuca** [comment]
Thanks @AlexandraKapp! We added the papers
